name:                styx-lang
version:             0.1.0.0
github:              "coffee-cup/styx"
license:             BSD3
author:              "Jake Runzer"
maintainer:          "jakerunzer@gmail.com"
copyright:           "2018 Jake Runzer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/coffee-cup/styx#readme>

dependencies:
- array
- base                 >= 4.7   && < 5
- containers           >= 0.5   && <0.6
- directory            >= 1.3   && <1.4
- haskeline            >= 0.7   && <0.8
- mtl                  >= 2.2   && <2.3
- optparse-applicative >= 0.14  && <0.15
- repline              >= 0.1.2
- text                 >= 1.2   && <1.3
- transformers         >= 0.5.2 && <0.6

library:
  source-dirs: src
  build-tools:
  - alex
  - happy

executables:
  styx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - styx-lang

tests:
  styx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - styx-lang
